
spring:
  profiles:
    active: dev
  thymeleaf:
    mode: HTML
  devtools:
    restart:
      trigger-file: .trigger



book:
  name: 互联网世界观
  author: 李善友
  isbn: ${random.uuid}
  description: ${book.name} ,这本书还不错


# application-{pro}.yml




